spring.application.name=rutech
spring.datasource.url=jdbc:postgresql://localhost:5432/rutech_db
spring.datasource.username=rutech_user
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
app.jwt.secret=${APP_JWT_SECRET}
app.jwt.expiration=${APP_JWT_EXPIRATION}
app.jwt.refresh-expiration=${APP_JWT_REFRESH_EXPIRATION}
file.upload-dir=./upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB